// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtIH-orFVrwS5weZmAiEHT6-Jch_cfYcc',
    appId: '1:587582559125:web:19d1dba52e23a285c05c9c',
    messagingSenderId: '587582559125',
    projectId: 'chat-app-8390f',
    authDomain: 'chat-app-8390f.firebaseapp.com',
    storageBucket: 'chat-app-8390f.firebasestorage.app',
    measurementId: 'G-TJ6T925HQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB4scI1RXqPnm8MN_U6rmx-fzrRITZH3k',
    appId: '1:587582559125:android:5f9903f3bb494285c05c9c',
    messagingSenderId: '587582559125',
    projectId: 'chat-app-8390f',
    storageBucket: 'chat-app-8390f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcwxxtXaJ0WoD7DZPaKJrG5DZKBEN0UEI',
    appId: '1:587582559125:ios:876739ec80699508c05c9c',
    messagingSenderId: '587582559125',
    projectId: 'chat-app-8390f',
    storageBucket: 'chat-app-8390f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcwxxtXaJ0WoD7DZPaKJrG5DZKBEN0UEI',
    appId: '1:587582559125:ios:876739ec80699508c05c9c',
    messagingSenderId: '587582559125',
    projectId: 'chat-app-8390f',
    storageBucket: 'chat-app-8390f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArfdyv0XJoeb_a8W0_T8wMDxVkH-bZZ4A',
    appId: '1:587582559125:web:0fef94a736d91a93c05c9c',
    messagingSenderId: '587582559125',
    projectId: 'chat-app-8390f',
    authDomain: 'chat-app-8390f.firebaseapp.com',
    storageBucket: 'chat-app-8390f.firebasestorage.app',
    measurementId: 'G-3R9JF766KT',
  );
}
